name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install

      - name: Lint with Biome
        run: |
          bun run check

      - name: Unit tests
        run: |
          bun test

      - id: semantic-release
        name: Run semantic-release
        run: |
          bunx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy default config
        run: |
          bun run config

      - name: Build
        run: |
          bun run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.semantic-release.outputs.nextVer != null }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yujiosaka/mcp-html-sync-server:${{ steps.semantic-release.outputs.nextVer }}
            yujiosaka/mcp-html-sync-server:latest
        if: ${{ steps.semantic-release.outputs.nextVer != null }}
